server:
  port: 8081

database:
  # Use 'postgres' and port 5432 when running in Docker
  # Use 'localhost' and port 5433 when running locally
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: qhronos

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

auth:
  master_token: "your-master-token-here"
  jwt_secret: "your-jwt-secret-here"

scheduler:
  look_ahead_duration: 24h   # How far into the future to expand recurring events
  expansion_interval: 5m     # How often to run the expander
  dispatch_worker_count: 1   # Number of dispatcher workers
  grace_period: 2m           # How far into the past to look for missed events

archival:
  check_period: 1h 

retention:
  events: 30d
  occurrences: 7d 

logging:
  level: "info"           # Log level: debug, info, warn, error
  file_path: "logs/qhronos.log" # Path to the log file
  max_size: 50            # Max size (MB) before rotation
  max_backups: 7          # Max number of old log files to retain
  max_age: 30             # Max age (days) to retain old log files 

# Dispatcher retry and backoff settings
# Number of times to retry dispatch (both HTTP and WebSocket)
dispatch_max_retries: 3
# Backoff duration between retries (e.g., 5s, 1m)
dispatch_retry_backoff: 5s 