version: '3.6'

services:

  postgres:
    image: postgres:14.7
    container_name: qhronos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qhronos
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - qhronos-network
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: qhronos_redis
    ports:
      - "6378:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - qhronos-network
    restart: unless-stopped
  
  qhronosd:
    image: qhronosd:latest
    container_name: qhronosd 
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8080"
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - CONFIG_PATH=/app/config.yml
    networks:
      - qhronos-network

networks:
  qhronos-network:
    driver: bridge