name: build-qhronos-scheduler

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
      BUILD_DIR: ./landing
      REGISTRY_ALIAS: w7r9n4j5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::816069145566:role/ECR-push-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up workflow env
        run: |
          echo "TAG=$(echo ${GITHUB_SHA::8})" >> $GITHUB_ENV
          echo "REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Build, tag, and push landing Docker image to Amazon ECR
        env:
          REPOSITORY: hera-qhronos-scheduler
          TARGET: hera-scheduler
        run: |
          docker build --target=$TARGET -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG $BUILD_DIR
          docker tag $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:${{ env.TAG }}
          docker push --all-tags $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY